### PR TITLE
Add support for .attachments in non-root folder

### PR DESCRIPTION
**Pull request by ricfre**
First of all - thank you for the great tool. Exactly what I have been looking for.

Small improvement:
In order to also manage an Azure Devops "code wikis" (https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki) I would like to suggest to allow the .attachments folder to be located in a subfolder.

For example, if I have a repo like this where the `wiki` folder represents my entire code wiki (simplified here of course):

```
$
  src
    ...
  wiki
    .attachments
      cat.png
    .order
    doc.md
```

I would like to be able to reference images in my markdown files like this: `/wiki/.attachments/cat.png` and still get it fixed during conversion.

The simple fix in this PR does the trick.

With that fix, it will be possible to have `.attachments` folders in:

* root of repo
* root of code-wiki folder
* any subfolder of the code-wiki folder

I would then just run the tool as usual with the `-s` arg pointing to the wiki folder.

### CODE REVIEW

**Comment by ricfre** [comment]
@phatcher Is this PR something you would be interested in? Please let me know if there is something you want me to change/update.

**Comment by phatcher** [comment]
@ricfre Apologies, had a decent break and only just picking this up - I think I've already subsumed this in a current branch as I had this issue internally as well but I'm trying to improve the testability of the code.

I should do a push in the next couple of days so you can see if it fixes your problem.

BTW Thanks for the PR, hopefully more people will find this project useful.

**Comment by ricfre** [comment]
@phatcher Ah, that sounds great! I will keep my eyes open for the new push. 
Thank you for the work. Let me know if I can assist in some way.

**Comment by phatcher** [comment]
@ricfre Can you checkout the feature/tests branch and see if works for your scenario now; I have tests showing copying of attachments in subfolders.

I'm also surprised that the earlier commit in October to fix attachment subfolders also wasn't good enough

**Comment by ricfre** [comment]
@phatcher Thank you for the update. I have now checked out the `feature/tests` branch and tested my use-case. Unfortunately it does not work.

My use case is related to having the entire wiki in a subfolder of the repo (meaning that the .attachments folder is not in the root of the repo, which in turn results in a situation where the image links cannot just start with /.attachments (well, they can from the AZ Devops point of view, but VS Code does not like it at all, making local editing a pain).

As simple way to repeat my use case is to modify the `src\WikiExport.Core.Test\Samples\Sample.wiki\S1\Bar.md` like below:
image

The test `ExporterFixture\DefaultOptions` test will now fail.
Adding my first commit (f4db670) fixes that.

My second commit (e8c8d19) is about maintaining the use of forwardslash in the resulting markdown. Mostly to keep things tidy, but also because I have found that popular VS Code plugins (like [Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf) for example) may have problems with the backslash.

Today I also realized that it would be good with an additional `?` in the regex in order to support image links of both these types:

* `.attachments/image.png`
* `../attachements/image.png`

The below still being supported of course.
* `/.attachments/image.png`

I have pushed the regex fix as well (7fa698c). I'm not that sure about the tests. I seems like I maybe should create another PR based on the `feature/tests` branch in order to add some specific tests for my use case?

**Comment by phatcher** [comment]
@ricfre I'll merge feature/tests down to main, if you update your PR to do the change your suggested to one of the image references and fix up the tests then I can accept it.

You can put a comment in the wiki page saying it shows an image from a non-root directory.

**Comment by phatcher** [comment]
@ricfre I've merged the changes back to main, you'll need to a few changes but shouldn't be too hard to fixup

**Comment by ricfre** [comment]
@phatcher I have now merged and adjusted to the new approach. Also added and adjusted some unit tests.

**Pull request merged**
